module.exports = {
  arrowParens: 'always',
  useTabs: false,
  tabWidth: 2,
  endOfLine: 'crlf',
  trailingComma: 'all',
  singleQuote: true,
  semi: false,
  bracketSpacing: true,
  printWidth: 120,
  singleAttributePerLine: true,
  jsxSingleQuote: false,
  bracketSameLine: false,
  plugins: ['prettier-plugin-tailwindcss'],
}
