import { type Listing } from '@/lib/listings'

export const __mock__listings: Listing[] = [
  {
    id: '1',
    brandName: 'Toyota',
    model: 'Camry',
    price: 10_000,
    type: 0,
    color: '#000000',
    clearance: 150,
    wheelSize: 17,
    mileage: 50000,
    year: 2018,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '2',
    brandName: 'Honda',
    model: 'CR-V',
    price: 10_000,
    type: 1,
    color: '#FF0000',
    clearance: 170,
    wheelSize: 18,
    mileage: 40000,
    year: 2019,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '3',
    brandName: 'Ford',
    model: 'F-150',
    price: 10_000,
    type: 0,
    color: '#FF0000',
    clearance: 200,
    wheelSize: 20,
    mileage: 60000,
    year: 2017,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '4',
    brandName: 'BMW',
    model: '3 Series',
    price: 10_000,
    type: 3,
    color: '#FF0000',
    clearance: 140,
    wheelSize: 19,
    mileage: 30000,
    year: 2020,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '5',
    brandName: 'Toyota',
    model: 'Rav4',
    price: 10_000,
    type: 4,
    color: '#FF0000',
    clearance: 180,
    wheelSize: 18,
    mileage: 35000,
    year: 2019,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '6',
    brandName: 'Honda',
    model: 'Civic',
    price: 10_000,
    type: 5,
    color: '#FF0000',
    clearance: 140,
    wheelSize: 16,
    mileage: 20000,
    year: 2021,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '7',
    brandName: 'Ford',
    model: 'Escape',
    price: 10_000,
    type: 5,
    color: '#FF0000',
    clearance: 160,
    wheelSize: 17,
    mileage: 45000,
    year: 2018,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '8',
    brandName: 'BMW',
    model: 'X5',
    price: 10_000,
    type: 0,
    color: '#FF0000',
    clearance: 190,
    wheelSize: 19,
    mileage: 25000,
    year: 2020,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '9',
    brandName: 'Toyota',
    model: 'Prius',
    price: 10_000,
    type: 6,
    color: '#FF0000',
    clearance: 140,
    wheelSize: 15,
    mileage: 30000,
    year: 2019,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '10',
    brandName: 'Honda',
    model: 'Accord',
    price: 10_000,
    type: 7,
    color: '#FF0000',
    clearance: 150,
    wheelSize: 17,
    mileage: 40000,
    year: 2018,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '11',
    brandName: 'Ford',
    model: 'Mustang',
    price: 10_000,
    type: 2,
    color: '#FF0000',
    clearance: 130,
    wheelSize: 18,
    mileage: 20000,
    year: 2020,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '12',
    brandName: 'BMW',
    model: 'X3',
    price: 10_000,
    type: 2,
    color: '#FF0000',
    clearance: 170,
    wheelSize: 19,
    mileage: 35000,
    year: 2019,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '13',
    brandName: 'Toyota',
    model: 'Highlander',
    price: 10_000,
    type: 3,
    color: '#FF0000',
    clearance: 190,
    wheelSize: 20,
    mileage: 50000,
    year: 2017,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '14',
    brandName: 'Honda',
    model: 'Pilot',
    price: 10_000,
    type: 4,
    color: '#FF0000',
    clearance: 200,
    wheelSize: 18,
    mileage: 45000,
    year: 2018,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '15',
    brandName: 'Ford',
    model: 'Focus',
    price: 10_000,
    type: 5,
    color: '#FF0000',
    clearance: 140,
    wheelSize: 16,
    mileage: 30000,
    year: 2020,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '16',
    brandName: 'BMW',
    model: '5 Series',
    price: 10_000,
    type: 6,
    color: '#FF0000',
    clearance: 150,
    wheelSize: 17,
    mileage: 40000,
    year: 2019,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '17',
    brandName: 'Toyota',
    model: 'Tacoma',
    price: 10_000,
    type: 7,
    color: '#FF0000',
    clearance: 180,
    wheelSize: 18,
    mileage: 60000,
    year: 2017,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
  {
    id: '18',
    brandName: 'Honda',
    model: 'Odyssey',
    price: 10_000,
    type: 8,
    color: '#FF0000',
    clearance: 160,
    wheelSize: 17,
    mileage: 35000,
    year: 2018,
    horsepower: null,
    engineVolume: null,
    engineType: null,
  },
]
